"use client";

import Head from "next/head";
import { Inter } from "@next/font/google";
import { FormEvent, useState } from "react";
import axios from "axios";

const inter = Inter({ subsets: ["latin"] });

export default function Classify() {
    const [walc, setWalc] = useState("")
    const [fedu, setFedu] = useState("")
    const [absence, setAbsence] = useState(0)
    const [g1, setG1] = useState(0)
    const [g2, setG2] = useState(0)


    const weekendAlcoholCategories = ["No alcohol", "1 to 3 shots", "3 to 5 shots", "5 to 8 shots", "More than 8 shots"];
    const feduCategories = ["No education", "Primary school", "Lower secondary (6th to 9th grade)", "Higher secondary (10th to 12th grade)", "Higher education"]


    function submitData(e: FormEvent<HTMLFormElement>) {
        e.preventDefault()
        axios.post("http://127.0.0.1:8000/classify", { g1, g2, absence, walc, fedu })
            .then((res) => {
                console.log("The response is ", res);
            })
    }

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className="m-auto mt-[10vh] w-full max-w-md rounded-lg border border-gray-200 bg-white bg-gradient-to-r from-pink-500 to-yellow-500 p-4 shadow-md sm:p-6 md:p-8 mb-36 ">
                <form
                    className="space-y-6"
                    onSubmit={(e) => submitData(e)}
                >
                    <h5 className="text-xl text-center font-bold underline text-white">
                        Classify your grade
                    </h5>

                    <GradeInput
                        title="g1"
                        desc="What is your year 1 grade? (On the scale of 0 to 20)"
                        max="20"
                        state={g1}
                        setStateFunc={setG1}
                    />
                    <GradeInput
                        title="g2"
                        desc="What is your year 2 grade? (On the scale of 0 to 20)"
                        max="20"
                        state={g2}
                        setStateFunc={setG2}
                    />
                    <GradeInput
                        title="absences"
                        desc="How many classes do you miss in the last academic year?"
                        max="93"
                        state={absence}
                        setStateFunc={setAbsence}
                    />
                    <RadioList
                        categories={weekendAlcoholCategories}
                        title="walc"
                        state={walc}
                        setStateFunc={setWalc}
                        desc="How much alcohol do you consume weekly?"
                    />
                    <RadioList
                        categories={feduCategories}
                        title="fedu"
                        state={fedu}
                        setStateFunc={setFedu}
                        desc="What was you father's highest education?"
                    />

                    <button
                        type="submit"
                        className="w-full from-cyan-500 to-blue-500 hover:from-indigo-500 hover:via-purple-500 hover:to-pink-500 rounded-lg bg-gradient-to-r  px-5 py-2.5 text-center text-sm font-medium text-white focus:outline-none focus:ring-4 focus:ring-blue-300 dark:focus:ring-blue-800"
                    >
                        Submit
                    </button>
                </form>
            </div >
        </>
    );
}

function GradeInput(props: { title: string, desc: string, max: string, state: any, setStateFunc: Function }) {

    const { title, desc, max, state, setStateFunc } = props;

    return (
        <div>
            <label htmlFor={title} className="mb-2 block text-lg font-medium text-gray-900 dark:text-white">
                {desc}
            </label>
            <input className="rounded w-[100px]" name={title} type="number" min="0" max={max} onChange={(e) => { setStateFunc(e.target.value) }} />
        </div>
    )
}

function RadioList(props: { categories: Array<string>, title: string, state: string, setStateFunc: Function, desc: string }): JSX.Element {
    const { categories, title, state, setStateFunc, desc } = props;
    return (
        <>
            <div>
                <label
                    className="mb-2 block text-lg font-medium text-gray-900 dark:text-white"
                >
                    {desc}
                </label>
                <fieldset>
                    {categories.map((category, index) => {
                        return (
                            <div className="mb-2 flex items-center" key={index}>
                                <input
                                    id={title + "-" + (index + 1).toString()}
                                    type="radio"
                                    value={title + "-" + (index + 1).toString()}
                                    name={`${title}-radio-` + (index + 1).toString()}
                                    checked={state === (index + 1).toString()}
                                    onChange={() => { setStateFunc((index + 1).toString()) }}
                                    className="h-4 w-4 bg-gray-100 text-blue-600  focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:ring-offset-gray-800 dark:focus:ring-blue-600"
                                />
                                <label
                                    htmlFor={title + "-radio" + (index + 1).toString()}
                                    className="ml-2 text-sm font-medium text-gray-900"
                                >
                                    {category}
                                </label>
                            </div>
                        )
                    })}
                </fieldset>
            </div>
        </>)
}
